### DISCUSSION TITLE
Fixing a static compile not working under sccache

### DISCUSSION THREAD

**Discussion by echelonh** [mozilla/sccache#2205] [Q&A]
Hi there!

I have numerous rust projects which I'm trying to speed up compilation times for. These are being compiled in a Gitlab CI environment, nothing too fancy. Hence, I'm using the pre-complied musl release binaries `v0.8.1`, not `cargo install sccache` in my CI container images.

For various reasons, I need these binaries to be statically linked, but when I'm using `sccache` (literally, the only change in the build environment), these binaries come out as dynamically linked anyway. Otherwise - they come out as static binaries and all is well.

I'm trying to understand if this is a known issue or if there's a way to solve it. 

(I read the README, but I was under the impression the openssl issue is for `sccache` itself, not the compilation target, correct me if I'm wrong?)

Compilation params:

`Cargo.toml`
```toml
[profile.release]
strip = "debuginfo"
opt-level = 3
lto = true
incremental = true
codegen-units = 1
```

`.cargo/config.toml`
```toml
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
```

`.gitlab-ci.yml`
```yml
.build:
  variables:
    SCCACHE_BUCKET: my-bucket
    SCCACHE_REGION: us-east-2
    SCCACHE_S3_KEY_PREFIX: sccache/$CI_PROJECT_PATH/
    RUSTC_WRAPPER: sccache
....
  script:
    cargo build --release --timings --locked --target $(uname -m)-unknown-linux-gnu
```

Thank you :pray: !
