### ISSUE TITLE
sccache: warning: The server looks like it shut down unexpectedly, compiling locally instead

### ISSUE THREAD

**Issue by GopherJ** [mozilla/sccache#1025]
I ran into this in CI,https://github.com/GopherJ/parallel/runs/3297218748?check_suite_focus=true

<img width="991" alt="image" src="https://user-images.githubusercontent.com/33961674/128979730-64617c89-5835-47db-90d1-e7377f8fd42f.png">

**Comment by GopherJ** [comment]
what does it mean?

**Comment by rakanalh** [comment]
I have also seen this problem on a private repo i am working on. 

The Github actions job looks as follows:
```yaml
  node-unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    continue-on-error: false
    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_S3_KEY_PREFIX: ${{ secrets.SCCACHE_S3_KEY_PREFIX }}
      SCCACHE_BUCKET: ${{ secrets.SCCACHE_BUCKET }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly-2021-04-18
          target: wasm32-unknown-unknown
          override: true
          default: true
      - name: Install sccache (ubuntu-latest)
        env:
          LINK: https://github.com/mozilla/sccache/releases/download
          SCCACHE_VERSION: v0.2.15
        run: |
          SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
          mkdir -p $HOME/.local/bin
          curl -L "$LINK/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
          mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
          chmod +x $HOME/.local/bin/sccache
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Cache cargo registry
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: |
              ~/.cargo/registry
              ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
              ${{ runner.os }}-cargo-
      - name: Start sccache server
        run: sccache --start-server
      - name: Unit Test (only Node and Pallets)
        run: cargo test --locked
      - name: Print sccache stats
        run: sccache --show-stats
      - name: Stop sccache server
        run: sccache --stop-server || true
```

We have 2 parallel builds both of which are using different `SCCACHE_S3_KEY_PREFIX` and `SCCACHE_BUCKET`.
One of those builds finishes in 6 minutes, with stats:
```
Compile requests                   1072
Compile requests executed           858
Cache hits                          858
Cache hits (C/C++)                   52
Cache hits (Rust)                   806
Cache misses                          0
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                 212
Non-compilation calls                 2
Unsupported compiler calls            0
Average cache write               0.000 s
Average cache read miss           0.000 s
Average cache read hit            0.139 s
Failed distributed compilations       0

Non-cacheable reasons:
crate-type                          185
unknown source language              15
-                                    12
- 
```
and the other in 45 minutes:
```
Compile requests                      4
Compile requests executed             1
Cache hits                            1
Cache hits (Rust)                     1
Cache misses                          0
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                   3
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.000 s
Average cache read miss           0.000 s
Average cache read hit            0.475 s
Failed distributed compilations       0

Non-cacheable reasons:
crate-type                            3
```

The latter case is caused by the fact that the error message described in this issue was displayed and the build restarted from scratch.
