### ISSUE TITLE
[hard to reproduce] setting cargo target-dir (to tmpfs?) can mess up the cache causing rebuilds

### ISSUE THREAD

**Issue by crumblingstatue** [mozilla/sccache#1054]
I'm sorry to write this down without a clear way to reproduce, but I really couldn't find any.
This seems to happen at random.
Here is a test Cargo.toml
```toml
[package]
name = "inventory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.2.8"
xlsxwriter = "0.3.5"
chrono = "0.4.19"
anyhow = "1.0.44"
thiserror = "1.0.30"
rusqlite = { version = "0.26.0", features = ["bundled"] }
```
Here is a .cargo/config.toml
```toml
build.target-dir="/tmp/cargo-builds/inventory"
```
If one spends enough time mucking about with these two files, creating projects that have them, enable/disable the .cargo/config.toml, it should be possible to reproduce this behavior.
It causes these packages to be recompiled every time

```
Compiling libsqlite3-sys v0.23.1
   Compiling bindgen v0.58.1
   Compiling rusqlite v0.26.0
   Compiling libxlsxwriter-sys v1.1.1
   Compiling xlsxwriter v0.3.5
```

Deleting $HOME/.cache/sccache will end the recompiling behavior until it is messed up again.

System: Arch Linux x86_64
rustc 1.57.0-nightly (41dfaaa3c 2021-10-10)
cargo 1.57.0-nightly (d56b42c54 2021-09-27)
sccache 0.2.15

I'm sorry for lack of better reproduction, I tried for more than an hour to make sense of this bug, and I have coding to do.
I might try returning to this later when I have more time. But in the meantime, I want to track this bug.
