### ISSUE TITLE
Add `winget` support on Windows

### ISSUE THREAD

**Issue by satvikpendem** [mozilla/sccache#1251]
`winget` is the official package manager for Windows that's built into Windows 11 now, so supporting it would be ideal for those of us already using it rather than `scoop` or `choco`.

**Comment by emabrey** [comment]
I'm looking into this.

**Comment by emabrey** [comment]
Looking into using the [YamlCreate](https://github.com/microsoft/winget-pkgs/blob/master/doc/tools/YamlCreate.md) tool to generate the manifest for this.

**Comment by emabrey** [comment]
Created this manifest, does anyone have any input?

```yaml
# Created with YamlCreate.ps1 v2.1.3 $debug=NVS2.5-1-19041-1682
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: Mozilla.sccache
PackageVersion: 0.3.0
PackageLocale: en-US
Publisher: Mozilla Foundation
PublisherUrl: https://www.mozilla.org/en-US/
PublisherSupportUrl: https://support.mozilla.org/en-US/ 
PrivacyUrl: https://www.mozilla.org/en-US/privacy/websites
Author: Ted Mielczarek, Alex Crichton
PackageName: sccache
PackageUrl: https://github.com/mozilla/sccache
License: Apache-2.0
LicenseUrl: https://github.com/mozilla/sccache/blob/main/LICENSE
CopyrightUrl: https://www.mozilla.org/en-US/foundation/trademarks/policy
ShortDescription: Sccache is an open-source code caching tool.
Description: |
              Sccache is a ccache-like tool. It is used as a compiler wrapper and avoids 
              compilation when possible, storing a cache in a remote storage using the
              S3 API.
Moniker: sccache
Tags:
- cache
- ccache
- sccache
- mozilla
- rust
- msvc
- gcc
- S3
- distributed
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
# PurchaseUrl: 
# InstallationNotes: 
# Documentations: 
ManifestType: defaultLocale
ManifestVersion: 1.2.0
```
