### ISSUE TITLE
Implement sscache-action to make github action users life easier

### ISSUE THREAD

**Issue by Xuanwo** [mozilla/sccache#1535]
To use sccache in GHA, users need to download sccache by themselves:

For example:

- https://github.com/indygreg/apple-platform-rs/blob/f69ad3207e9a4898e338fbf1a2b24b9985fb5a03/Justfile#L16-L42
- https://github.com/sylvestre/coreutils/blob/d49759d76362de7bfb05ab59caba5cf1606b9aff/util/install-sccache.sh#L1-L23

By introducing `sscache-action`, we can use it as simple as:

```yaml
- uses: mozilla/sccache-action@v1
  with:
    start: true # start as soon as installed
    show_stat: true # print stat after job finished (via action hook)
  env:
    SCCACHE_GHA_VERSION: happy_new_year
```
