### ISSUE TITLE
sccache-dist scheduler get a signal 11 received in alpine(virt-machine)

### ISSUE THREAD

**Issue by huang12zheng** [mozilla/sccache#1589]
```sh
cargo build --features="dist-client dist-server"
```
> success
```sh
localhost:~/sccache/target/debug$ export SCCACHE_LOG=1 SCCACHE_NO_DAEMON=1 RUST_LOG=trace; ./sccache-dist scheduler --config ./scheduler.conf --syslog debug

signal 11 received
Segmentation fault

localhost:~/sccache/target/debug$ uname -a

Linux localhost 5.15.90-0-lts #1-Alpine SMP Tue, 24 Jan 2023 09:18:58 +0000 x86_64 Linux
```
>alpine 16.3

```toml
[dist]
# The URL used to connect to the scheduler (should use https, given an ideal
# setup of a HTTPS server in front of the scheduler)
scheduler_url = "https://192.168.0.114:10600"
# scheduler_url = "https://127.0.0.1"
# Used for mapping local toolchains to remote cross-compile toolchains. Empty in
# this example where the client and build server are both Linux.
toolchains = []
# Size of the local toolchain cache, in bytes (5GB here, 10GB if unspecified).
toolchain_cache_size = 5368709120

[dist.auth]
type = "token"
# This should match the `client_auth` section of the scheduler config.
token = "my client token"
```

question:
what's that mean?
```
signal 11 received
Segmentation fault
```
And What did I miss?
