### ISSUE TITLE
[BUG] `SCCACHE_S3_NO_CREDENTIALS=true` stopped working in `0.5.0`

### ISSUE THREAD

**Issue by ajschmidt8** [mozilla/sccache#1799]
It seems that the `SCCACHE_S3_NO_CREDENTIALS=true` configuration stopped working in `0.5.0`.

When using the following configuration with a publicly readable bucket with `sccache` version `0.4.2`, `sccache` compiles correctly:

```
SCCACHE_BUCKET=<publicly_readable_bucket>
SCCACHE_IDLE_TIMEOUT=32768
SCCACHE_REGION=us-east-2
SCCACHE_S3_NO_CREDENTIALS=true
SCCACHE_S3_USE_SSL=true
```

However, in the same environment, `sccache` version `0.5.0` throws the following error message:

```
sccache: error: Server startup failed: cache storage failed to read: PermissionDenied (temporary) at read => no valid credential found, please check configuration or try again
    
    Context:
        service: s3
        path: .sccache_check
        range: 0-
    
    Run with SCCACHE_LOG=debug SCCACHE_NO_DAEMON=1 to get more information
```

The issue exists in `0.5.3` as well.

Setting `SCCACHE_LOG=debug` and  `SCCACHE_NO_DAEMON=1` did not seem to provide any additional details.
