### ISSUE TITLE
0.6.0 regression: region is not read even if it is set in `~/.aws/credentials`

### ISSUE THREAD

**Issue by imWildCat** [mozilla/sccache#1925]
My `~/.aws/credentials` file:

```toml
[default]
aws_access_key_id = ...
aws_secret_access_key = ...
region = us-east-1
aws_region = us-east-1
sccache_region = us-east-1
```

Error:

```
Caused by:
  process didn't exit successfully: `/opt/homebrew/bin/sccache /Users/catlab/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 2)
  --- stderr
  sccache: error: Server startup failed: create s3 cache failed: ConfigInvalid (permanent) at Builder::build, context: { service: s3 } => region is missing. Please find it by S3::detect_region() or set them in env.

  Stack backtrace:
     0: __mh_execute_header
     1: __mh_execute_header
     2: __mh_execute_header
     3: __mh_execute_header
     4: __mh_execute_header
     5: __mh_execute_header
     6: __mh_execute_header
     7: __mh_execute_header
```
