### ISSUE TITLE
Local disk cache never increases beyond 10 GB

### ISSUE THREAD

**Issue by clin1234** [mozilla/sccache#2172]
My config in `%APPDATA%\Mozilla\sccache\config\config`:
```toml
[cache.disk]
size = 27516192768
```

Yet `sccache -s` shows that the maximum cache size remains at 10 GB.

**Comment by brian6932** [comment]
I'm having the same problem `SCCACHE_CACHE_SIZE` set in env.

**Comment by glandium** [comment]
> I'm having the same problem with `SCCACHE_CACHE_SIZE` set in env.

This one is addressed in #2183



> My config in `%APPDATA%\Mozilla\sccache\config\config`:
> 
> ```toml
> [cache.disk]
> size = 27516192768
> ```
> 
> Yet `sccache -s` shows that the maximum cache size remains at 10 GB.

I can't reproduce this.

**Comment by clin1234** [comment]
Just compiled from `HEAD`, max cache size still limited to 10G. Here's the config in `%localappdata%\Mozilla\sccache\config\config`
```toml
[cache.disk]
size = 27G
```

**Comment by just-an-engineer** [comment]
@clin1234, I also can't reproduce this, although I'm on Linux. But putting `27G` gives me
```
sccache: error: Failed to load config file
sccache: caused by: Failed to load toml config file from /home/julian/.config/sccache/config
sccache: caused by: TOML parse error at line 2, column 10
  |
2 | size = 27G
  |          ^
expected newline, `#`
```
Can you verify that sccache is correctly reading in your config file, properly parsing the 27G, and still only displaying 10 GiB?
Or, if the `G` was a placeholder for all those trailing numbers, then when I put in `size = 27516192768`, it _does_ properly show the new max cache. In which case I also can't recreate this issue.

**Comment by clin1234** [comment]
```
$ SCCACHE_LOG=debug SCCACHE_START_SERVER=1 SCCACHE_NO_DAEMON=1 sccache
[2024-08-12T21:12:33Z DEBUG sccache::config] Attempting to read config file at "C:\\Users\\ךינשגכהד\\AppData\\Roaming\\Mozilla\\sccache\\config\\config"
[2024-08-12T21:12:33Z DEBUG sccache::config] Couldn't open config file: failed to open file `C:\Users\ךינשגכהד\AppData\Roaming\Mozilla\sccache\config\config`
[2024-08-12T21:12:33Z INFO  sccache::server] start_server: port: 4226
[2024-08-12T21:12:33Z INFO  sccache::server] No scheduler address configured, disabling distributed sccache
[2024-08-12T21:12:33Z DEBUG sccache::cache::cache] Init disk cache with dir "C:\\Users\\ךינשגכהד\\AppData\\Local\\Mozilla\\sccache\\cache", size 10737418240
[2024-08-12T21:12:33Z INFO  sccache::server] server has setup with ReadWrite
[2024-08-12T21:12:33Z INFO  sccache::server] server started, listening on port 4226

```

Copied the following config to the right directory:
```toml
[cache.disk]
size = 27516192768

# See the local docs on more explanations about this mode
[cache.disk.preprocessor_cache_mode]
# Whether to use the preprocessor cache mode
use_preprocessor_cache_mode = true
# Whether to use file times to check for changes
file_stat_matches = true
# Whether to also use ctime (file status change) time to check for changes
use_ctime_for_stat = true
# Whether to ignore `__TIME__` when caching
ignore_time_macros = false
# Whether to skip (meaning not cache, only hash) system headers
skip_system_headers = false
# Whether hash the current working directory
hash_working_directory = true
```

And `sccache --show-stats` confirms the cache size did change:
```
C:\Users\ךינשגכהד\AppData\Local\Mozilla\sccache>sccache --show-stats
Compile requests                      0
Compile requests executed             0
Cache hits                            0
Cache misses                          0
Cache hits rate                       -
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                   0
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.000 s
Average compiler                  0.000 s
Average cache read hit            0.000 s
Failed distributed compilations       0
Cache location                  Local disk: "C:\\Users\\ךינשגכהד\\AppData\\Local\\Mozilla\\sccache\\cache"
Use direct/preprocessor mode?   yes
Version (client)                0.8.1
Max cache size                       26 GiB
```
