### ISSUE TITLE
Support S3 Express One Zone

### ISSUE THREAD

**Issue by Fraccaman** [mozilla/sccache#2220]
Is [S3 Express One Zone](https://aws.amazon.com/s3/storage-classes/express-one-zone/) supported? I'm not sure if I am during something wrong but 
```
Compile requests                    963
Compile requests executed           654
Cache hits                            0
Cache misses                        654
Cache misses (Rust)                 654
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                  654
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                 [30](https://github.com/Fraccaman/namada/actions/runs/9898192480/job/27344414279#step:11:31)9
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.000 s
Average compiler                  0.465 s
Average cache read hit            0.000 s
Failed distributed compilations       0
```
using the followings sccache configuration
```
env:
  RUSTC_WRAPPER: sccache
  SCCACHE_S3_USE_SSL: false
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: full
  SCCACHE_BUCKET: $NAME--usw2-az1--x-s3
  AWS_REGION: $REGION
```
